### ISSUE TITLE
Práctica 6_Reconocimiento de imágenes

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo_prestadores#2]
[Práctica 6_Reconocimiento de imagenes.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo_prestadores/files/8600654/Practica.6_Reconocimiento.de.imagenes.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Buen trabajo
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
